### ISSUE TITLE
Bootargs issue

### ISSUE THREAD

**Issue by rprasanth** [ADVANTECH-Corp/uboot-imx6#1]
Hi Team,

Could you please clarify the code snip in common/board_r.c file, why its done so?
`	sprintf(buf, "advboot_version=%s uboot_version=%s", advboot_version, uboot_version);
#ifdef CONFIG_ANDROID_SUPPORT
	setenv("bootargs_adv", buf);
#else
	setenv("bootargs", buf);
#endif`

I expect this is causing the bootargs to get with some unwanted values "advboot_version=%s uboot_version=%s" instead of the original bootargs?

**Comment by daniel6096** [comment]
Our u-boot both supports Android & Linux yocto, and it can be identified by `CONFIG_ANDROID_SUPPORT` flag. In the code snip you pasted, we attempt to add _advboot_version_ & _uboot_version_ into kernel parameters. However, there is an unexpected parameter in Android called `androidboot.serialno`. This parameter is handled in `common/image-android.c` file. There's also where we add the _advboot_version_ actually. In Linux, we do not need this serial no. So, we can handle in `common/board_r.c` file directly.

**Comment by rprasanth** [comment]
Hi Daniel,
Thanks for the reply,
But I could see the bootargs is updated with only "bootargs=advboot_version= uboot_version=2016.03", which keep on replace the above value whenever a reset or reboot is done.
Any idea on this?

**Comment by daniel6096** [comment]
@rprasanth 

I'm not very sure what your question is, but I suspect you want to add some args into bootargs, however, it is always overwrited with only adv_version & uboot_version.
If that is the case, you should use `mmcargs` instead of `bootargs`.
You can append your new args in mmcargs.
`mmcargs=setenv bootargs console=${console},${baudrate} ${smp} root=${mmcroot} ${bootargs}`

**Comment by rprasanth** [comment]
Oh, then you mean that on every reboot, I need to run mmcargs? but, I am looking for autobooting. instead of running mmcargs or updating the bootargs everytime?

**Comment by daniel6096** [comment]
No. You should use `saveenv` after `setenv`. Then, the parameters will be stored in SPI nor flash. To clean the saved parameters, use `env default -a` and `saveenv` again.

**Comment by rprasanth** [comment]
Ya, that's the exact way I follow for all the boards. But, in this case, it doesn't work. Could you try once by yourself with the hardware?

it always hangs in the starting kernel, as the bootargs was not getting the console and root values. I hope this time, I have clarified my issue.

**Comment by daniel6096** [comment]
Could you provide the detailed commands for me? BTW, which branch do you test?

**Comment by rprasanth** [comment]
ADVANTECH-Corp/uboot-imx6
imx6LBV8540.tar.gz

I have the SPL loaded by using mfg tool already,
The command used are:
dd the o/p to SD card
$ sudo dd if=u-boot_crc.bin.crc of=/dev/sdb bs=512 seek=2 conv=fsync 
$ sudo dd if=u-boot_crc.bin of=/dev/sdb bs=512 seek=3 conv=fsync 

u-boot-log
U-Boot 2016.03 (Apr 17 2018 - 11:42:11 +0530)

CPU:   Freescale i.MX6DP rev1.0 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 39C
Reset cause: POR
Board: MX6-SabreSD
I2C:   ready
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
JEDEC ID: 0x20:0xba:0x16
In:    serial
Out:   serial
Err:   serial
JEDEC ID: 0x20:0xba:0x16
MAC address is invailed !!
Use default MAC adderss:0x00:0x04:0x9F:0x01:0x30:0xE0
booting from SD
.....
=> run mmcargs
=> saveenv
Saving Environment to SPI Flash...
JEDEC ID: 0x20:0xba:0x16
Erasing SPI flash...Writing to SPI flash..................................SUCCESS
done
=>boot

to be noticed:
=> run mmcargs
=> printenv bootargs
bootargs=console=ttymxc0,115200 root=/dev/mmcblk1p2 rootwait rw advboot_version= uboot_version=2016.03
=> saveenv
Saving Environment to SPI Flash...
JEDEC ID: 0x20:0xba:0x16
Erasing SPI flash...Writing to SPI flash..................................SUCCESS
=> printenv bootargs 
bootargs=console=ttymxc0,115200 root=/dev/mmcblk1p2 rootwait rw advboot_version= uboot_version=2016.03

After reset(in uboot) or reboot(from userspace)
=>reset
$ reboot
=> printenv bootargs
bootargs=advboot_version= uboot_version=2016.03

This is the issue, which hangs

**Comment by timliangtw** [comment]
Hi,
I find the cause of your problem, because the debug port of this product is ttymxc1 instead of ttymxc0
So I think you  can use `env default -a` then `saveenv ` or `setenv console ttymxc1` then `saveenv`.

**Comment by rprasanth** [comment]
Hi Tim,
Sorry, this doesn't work, the issue is with the bootargs, not with the console. Kindly verify by booting the hardware and repeat the steps as I mentioned above, You will get my point.

**Comment by daniel6096** [comment]
@rprasanth Because we have many boards with different design, could I know the hardware model on your hand? Is that EBC-RS03? If you don't know, you may try `cat /proc/board`.

**Comment by rprasanth** [comment]
rom-7421qp_a1, I didn't see this issue only on specific board. As the board_r.c file is used commonly for all the boards this will affect all the supported boards, I think.

Have you recreated my issue?

**Comment by rprasanth** [comment]
I'm trying to sort out the issue. But, Could you clarify me, why we are taking the adv_version and u-boot version into bootargs? That's the question, I can't clear myself.

**Comment by alex6235** [comment]
Hi rprasanth,
1. Can you tell me how to get this BSP (imx6LBV8540.tar.gz)?
2. You said "I have the SPL loaded by using mfg tool already" yesterday, but you provided following command to update u-boot image. It doesn't update command for SPL image.
$ sudo dd if=u-boot_crc.bin.crc of=/dev/sdb bs=512 seek=2 conv=fsync
$ sudo dd if=u-boot_crc.bin of=/dev/sdb bs=512 seek=3 conv=fsync
3. Did you update SPL image or u-boot image?

**Comment by rprasanth** [comment]
I build the bsp with yocto and cloned the latest sources from this repository.
Spl was flashed in nand, and u-boot was written to SD card.
I used the latest u-boot from your repo.

**Comment by rprasanth** [comment]
Now, I understood the flow of booting. I am explaining it for confirmation.
While  running "boot" this search for mmc and if not it goes for netboot. if it got success in mmc, it runs mmcboot, where mmc agrs sets the bootargs as needed for the board
`mmcargs=setenv bootargs console=${console},${baudrate} ${smp} root=${mmcroot} ${bootargs}`

**Comment by alex6235** [comment]
So is there a problem now?
If you still have a problem, please tell me update command for SPL image, duplicate issue steps and full log.

**Comment by rprasanth** [comment]
I am asking for the clarification of this part 
`bootargs=advboot_version= uboot_version=2016.03-imx_v2016.03_4.1.15_2.0.0_ga+g0f5bab8`
why this is passed to bootargs, can't we pass this advboot and uboot_version to some other variable instead of bootargs?
is there any specific reason to pass the values to bootargs?

**Comment by alex6235** [comment]
Of course. You can modify the settings by yourself.

**Comment by alex6235** [comment]
We pass the values to bootargs because it is a consideration for our product development.
In addition, please do not update the SPL image. This may cause the device cannot boot.

**Comment by rprasanth** [comment]
oh thanks.. Have a nice day
